### PR TITLE
Audit errors now prevent promo codes creative

### LINKED ISSUE #14: Audit errors don't prevent promo codes creation
```go
if err := h.auditStorage.Save(auditLog); err != nil {
	slog.Error("failed to save audit log",
		slog.Group("error",
			slog.String("message", err.Error()),
			slog.String("component", "auditStorage.Save")))
}
```

If we create a promo code, when no audit is available, we won't be able to investigate, who created it, in the future. This is a fatal error, and transaction must be rolled baked.

### PR DESCRIPTION
**Pull request by MikebangSfilya**
Resolve #14

### CODE REVIEW

File: internal/db/repo/promoRepo_test.go [hunk 1]
```diff
@@ -38,14 +38,14 @@ func setupTestDB(t *testing.T) (*pgxpool.Pool, func()) {
...
 	_, err = pool.Exec(ctx, `
-		CREATE TABLE IF NOT EXISTS Promo_Codes (
-			code varchar(16) PRIMARY KEY,
-			bonus_length integer NOT NULL,
-			since date NOT NULL DEFAULT current_date,
-			until date,
-			capacity integer NOT NULL CHECK ( capacity >= 0 )
-		);
-	`)
+       CREATE TABLE IF NOT EXISTS Promo_Codes (
```
Comment (kozalosev) [inline internal/db/repo/promoRepo_test.go]: Here's now spaces, not tabs

File: internal/db/repo/promoRepo.go [hunk 2]
```diff
@@ -1,23 +1,29 @@
...
 	models "github.com/MikebangSfilya/promoBot/internal/model"
+	"github.com/jackc/pgx/v5/pgconn"
 	"github.com/kozalosev/goSadTgBot/base"
 )
 
 type Promo struct {
 	appEnv *base.ApplicationEnv
 }
 
+type Execer interface {
```
Comment (kozalosev) [inline internal/db/repo/promoRepo.go]: 🤔 You can return a finalizer instead. See another comment below for more information

File: internal/db/repo/promoRepo_test.go [hunk 3]
```diff
@@ -170,17 +170,15 @@ func TestPromo_GetTable(t *testing.T) {
 	assert.Equal(t, "PROMO1", result[1].Code) // capacity = 10
 	assert.Equal(t, "PROMO3", result[2].Code) // capacity = 15
 
-	// Проверяем данные первого промокода
+	// Проверяем данные
```
Comment (kozalosev) [inline internal/db/repo/promoRepo_test.go]: In English, please

File: internal/handlers/promo.go [hunk 4]
```diff
@@ -163,7 +165,19 @@ func (h *PromoHandler) action(reqenv *base.RequestEnv, msg *tgbotapi.Message, fi
 
 	switch confirmAct {
 	case actionCreate:
-		err := h.PromoService.CreatePromo(modelToRepo)
+
+		ctxTr, cancel := context.WithTimeout(h.appEnv.Ctx, 5*time.Second)
+		defer cancel()
+		tx, err := h.appEnv.Database.Begin(ctxTr)
```
Comment (kozalosev) [inline internal/handlers/promo.go]: Don't create transactions here. This is a business logic handling layer. Database transactions are specific for database repositories. You can return a finalizer from the `promoRepo` instead:

```go
type TxFinalizer struct {
	tx pgx.Tx
}

func (f TxFinalizer) Commit(ctx context.Context) error {
	return f.tx.Commit(ctx)
}

func (f TxFinalizer) Rollback(ctx context.Context) {
	if err := f.tx.Rollback(ctx); err != nil {
         // error logging
    }
}

// <...>

func (p *Promo) CreatePromo(ctx context.Context, promoCode models.PromoCode) (TxFinalizer, error) {
// <...>
tx, err := p.appEnv.Database.Begin(ctx)
// error handling
_, err := tx.Exec(
// <...>

// in case of error:
// (I think if we return an empty struct, methods above must handle the case when tx is nil; nil reference also may be used here)
return TxFinalizer{}, err

// in case of success:
return TxFinalizer{tx: tx}, nil
```

Then in the handler you just call either `Commit()` or `Rollback()`.

**Review by kozalosev — CHANGES_REQUESTED** [review]

**Review by kozalosev — APPROVED** [review]
Super! Thanks! 🌟
